// xpic-web/src/app.tsx
import {convertFileSrc, invoke} from "@tauri-apps/api/tauri";
import "lightgallery/css/lightgallery-bundle.css";
import lgThumbnail from "lightgallery/plugins/thumbnail";
import lgZoom from "lightgallery/plugins/zoom";
import LightGallery from "lightgallery/react";
import "overlayscrollbars/overlayscrollbars.css";
import {useEffect, useState} from "react";
import "./app.css";
import {OverlayScrollbarsComponent} from "overlayscrollbars-react";

function App() {
    const [wallpapers, setWallpapers] = useState<string[]>([]);

    useEffect(() => {
        invoke<string[]>("get_wallpapers").then((wallpapers) =>
            setWallpapers(wallpapers),
        );

        invoke<string[]>("update_wallpapers").then((wallpapers) =>
            setWallpapers(wallpapers),
        );

        if (import.meta.env.MODE !== "development") {
            document.addEventListener("contextmenu", event => event.preventDefault())
        }
    }, []);

    const getName = (path: string): string => {
        const match = path.trim().match(/[^/\\]+$/);
        return match ? match[0] : "";
    };

    return (
        <>
            <OverlayScrollbarsComponent defer>
                <div className={"w-screen h-screen"}>
                    <LightGallery elementClassNames={"flex flex-wrap items-center justify-center py-8 px-4"}
                        plugins={[lgZoom, lgThumbnail]}
                        speed={500}
                        thumbnail={true}
                    >
                        {wallpapers.map((v) => (
                            <a href={convertFileSrc(v)} className={"p-3"} draggable={false}>
                                <img
                                    src={convertFileSrc(v)}
                                    alt={getName(v)}
                                    width={240}
                                    height={135}
                                    className={"rounded hover:brightness-125 hover:drop-shadow"}
                                />
                            </a>
                        ))}
                    </LightGallery>
                </div>
            </OverlayScrollbarsComponent>
        </>
    );
}

export default App;

// xpic-web/src/app.svelte
<script lang="ts">
    import {onMount} from "svelte";
    import {convertFileSrc, invoke} from "@tauri-apps/api/tauri";
    import {appWindow, LogicalSize} from "@tauri-apps/api/window";
    import {basename} from "@tauri-apps/api/path";
    import 'overlayscrollbars/overlayscrollbars.css';
    import {OverlayScrollbarsComponent} from "overlayscrollbars-svelte";

    let wallpapers = $state([] as string[]);
    // get base names for wallpapers
    let names = $derived(
        wallpapers.reduce<{ [key: string]: string }>((r, path) => {
            basename(path).then(name => {
                r[path] = name
            });
            return r
        }, {})
    )

    // get and update wallpapers
    onMount(() => {
        invoke<string[]>("get_wallpapers").then(r => {
            wallpapers = r
        });

        invoke<string[]>("update_wallpapers").then(r =>
            wallpapers = r
        );
    })

    // disable default context menu
    onMount(() => {
        if (import.meta.env.MODE !== "development") {
            document.addEventListener("contextmenu", (event) =>
                event.preventDefault(),
            );
        }
    })

    let gallery: HTMLDivElement

    const config = {
        default: {
          cols: 4,
          rows: 4,
        },
        img: {
            width: 240,
            height: 135,
        },
        gallery: {
            gap: 32,
            paddingX: 64,
            paddingY: 32,
        },
    }

    // set windows default size and min size
    onMount(() => {
        const defaultWindowSize = new LogicalSize(
            config.default.cols * config.img.width + (config.default.cols - 1) * config.gallery.gap + config.gallery.paddingX * 2,
            config.default.rows * config.img.height + (config.default.rows - 1) * config.gallery.gap + config.gallery.paddingY * 2,
        );
        const minWindowSize = new LogicalSize(
            config.img.width + config.gallery.paddingX * 2,
            config.img.height + config.gallery.paddingY * 2
        );

        appWindow.setSize(defaultWindowSize).then(() => {
            void appWindow.center();
        });
        void appWindow.setMinSize(minWindowSize);
    })

    function computeCols(): Number {
        // cols * width + (cols - 1) * gap + px * 2
        return Math.floor((window.innerWidth - config.gallery.paddingX * 2 + config.gallery.gap) / (config.img.width + config.gallery.gap));
    }

    function adjustCols() {
        gallery.style.gridTemplateColumns = `repeat(${computeCols()}, minmax(0, 1fr))`;
    }

    // set cols
    onMount(() => {
        adjustCols()
        window.addEventListener("resize", adjustCols)
    })
</script>

<main>
    <OverlayScrollbarsComponent defer>
        <div class="w-screen h-screen grid items-center justify-center">
            <div id="gallery" bind:this={gallery}
                 class="grid grid-cols-4 gap-8 items-center justify-center py-8 px-16"
            >
                {#each wallpapers as path}
                    <img src={convertFileSrc(path)}
                         alt={names[path]}
                         width={config.img.width}
                         height={config.img.height}
                         class="wallpaper rounded hover:brightness-125 hover:drop-shadow"
                    />
                {/each}
            </div>
        </div>
    </OverlayScrollbarsComponent>
</main>

<style>
</style>
